### PR TITLE
Update BackTrack Tab History

### PR DESCRIPTION
**Pull request by AlexVallat**
Firefox 97 has introduced sessionHistoryInParent which needs reworking of BackTrack Tab History for compatibility

### CODE REVIEW

**Comment by mzso** [comment]
[**@AlexVallat**](https://github.com/AlexVallat) commented on [2022. jan. 30. 11:17 CET](https://github.com/xiaoxiaoflood/firefox-scripts/pull/116#issue-1118482565 "2022-01-30T10:17:18Z - Replied by Github Reply Comments"):
> Firefox 97 has introduced sessionHistoryInParent which needs reworking of BackTrack Tab History for compatibility

What does this feature do by the way?

**Comment by AlexVallat** [comment]
> What does this feature do by the way?

I think this is part of the Fission effort. This particular change means that rather than getting session history within the content process from `docShell.sessionHistory.legacySHistory`, the session history is now obtained from the chrome process, from `tabBrowser.browsingContext.sessionHistory`. It's arguably a much more sensible and convenient place for it, and removes a bunch of content/chrome IPC that was previously required, but it did also mean a fair amount of work for me to change everything over.

For a user, if everyone has done their job correctly, it means no change in behaviour at all.

**Comment by xiaoxiaoflood** [comment]
Thanks. But please, what do you think about disabling `console.log` spamming? BTTH is logging hundreds of time per second on my profile and there is no benefit for the final user, I think this should only be enabled on your testing environment, not in release build.

**Comment by AlexVallat** [comment]
Agreed, the logging should have been disabled. Also, though, it should never be logging hundreds of times per second even when enabled, can you tell me what message is being spammed so much? I would only expect log messages when things happen (tabs open, mouse clicks, etc.) not continually in the background.

**Comment by xiaoxiaoflood** [comment]
I disabled logging right after my previous comment, so I don't know, but I remember seeing in the log the title of tabs that I weren't using at the moment (I have more than 100 open tabs). But I wasn't exaggerating, I think it was more than 100 per second. Probably not *every* second, but all the time I click somewhere, switch tabs, open tabs, so...

**Pull request merged**
