### PR TITLE
Disable debug logging in BackTrack Tab History

### PR DESCRIPTION
**Pull request by AlexVallat**
https://github.com/xiaoxiaoflood/firefox-scripts/issues/116#issuecomment-1027508848

### CODE REVIEW

**Comment by xiaoxiaoflood** [comment]
Thanks. Don't you intend to bump the version? Otherwise no one will get the update.

**Comment by AlexVallat** [comment]
OK, done

**Comment by mzso** [comment]
[**@AlexVallat**](https://github.com/AlexVallat) commented on [2022. febr. 3. 09:12 CET](https://github.com/xiaoxiaoflood/firefox-scripts/pull/117#issuecomment-1028709302 "2022-02-03T08:12:38Z - Replied by Github Reply Comments"):
> OK, done

Can I upgrade on a previous version of FF, or does it only work starting from 97?

**Comment by xiaoxiaoflood** [comment]
https://github.com/xiaoxiaoflood/firefox-scripts/blob/291bebc4f2edc919dd273f2cecbbfda61e157695/extensions/backtrack/update.rdf#L8

**Comment by AlexVallat** [comment]
> Can I upgrade on a previous version of FF, or does it only work starting from 97?

I only test under Firefox developer edition. I would say "probably not" for a previous version, but as sessionHistoryInParent was gated behind a config setting it's at least possible that if this is set true it might work on a previous version. There is no benefit to upgrading if the old version still works for you, though, so if you are using an older version of FF that doesn't do sessionHistoryInParent then use BackTrackTab History v0.34: https://github.com/xiaoxiaoflood/firefox-scripts/raw/b901b82e010e87dd0c993cc19435248e490fe975/extensions/backtrack/BackTrack.xpi

**Pull request merged**
